name: Update Notion Table on Push to Master

on:
  push:
    branches:
      - master

jobs:
  update_notion:
    name: Update Notion Table
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # 指定 Node.js 的版本

      - name: Run notion.js script
        run: |
          npm install
          node index.js
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_AUTHORIZATION }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_HABIT_PAGE_DATABASE_ID }}
