name: Update Notion Table on Push to Master

on:
  push:
    branches:
      - master

jobs:
  update_notion:
    name: Update Notion Table
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Latest Page ID from Notion Database
        id: fetch_latest_page
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          LATEST_PAGE_DATA=$(curl -X POST 'https://api.notion.com/v1/databases/${NOTION_DATABASE_ID}/query' \
          -H 'Authorization: ${NOTION_API_KEY}' \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{"page_size": 1, "sorts": [{"timestamp": "created_time", "direction": "descending"}]}')
          LATEST_PAGE_ID=$(echo $LATEST_PAGE_DATA | jq -r '.results[0].id')
          echo "::set-output name=latest_page_id::$LATEST_PAGE_ID"

      - name: Update Notion Table View Cell with Latest Page ID
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_PROPERTY_ID: ${{ secrets.NOTION_PROPERTY_ID }}
          NEW_VALUE: 'Your new value here'
        run: |
          curl -X PATCH "https://api.notion.com/v1/pages/${{ steps.fetch_latest_page.outputs.latest_page_id }}" \
          -H 'Authorization: Bearer ${NOTION_API_KEY}' \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "properties": {
              "${NOTION_PROPERTY_ID}": {
                "type": "title",
                "title": [
                  {
                    "text": {
                      "content": "${NEW_VALUE}"
                    }
                  }
                ]
              }
            }
          }'
